root = "."
tmp_dir = "tmp"
[build]
cmd = "templ generate && go build -o ./tmp/main ./cmd/server/main.go"
bin = "./tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", ".git", "web/static"]
exclude_file = ["*.sql", "*.md"]
exclude_regex = [".*_test.go", ".*_templ.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
kill_delay = "1s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
